package com.schautup.data;

import com.doomonafireball.betterpickers.recurrencepicker.EventRecurrence;

/**
 * Data structure of a schedule item.
 */
public final class ScheduleItem {
	/**
	 * Possible Id if data instance is from DB.
	 */
	private long mId;
	/**
	 * Different types scheduled.
	 */
	private ScheduleType mType;
	/**
	 * Hour.
	 */
	private int mHour;
	/**
	 * Minute.
	 */
	private int mMinute;
	/**
	 * Edited time.
	 */
	private long mEditedTime;
	/**
	 * The {@link com.doomonafireball.betterpickers.recurrencepicker.EventRecurrence}.
	 */
	private EventRecurrence mEventRecurrence;
	/**
	 * The reserve data for some settings.
	 */
	private String mReserveLeft;
	/**
	 * The reserve data for some settings.
	 */
	private String mReserveRight;

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param id
	 * 		Possible Id if data instance is from DB.
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 * @param editedTime
	 * 		Created time.
	 */
	public ScheduleItem(long id, ScheduleType type, int hour, int minute, long editedTime) {
		mId = id;
		mType = type;
		mHour = hour;
		mMinute = minute;
		mEditedTime = editedTime;
	}

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param id
	 * 		Possible Id if data instance is from DB.
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 */
	public ScheduleItem(long id, ScheduleType type, int hour, int minute) {
		this(id, type, hour, minute, System.currentTimeMillis());
	}

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 */
	public ScheduleItem(ScheduleType type, int hour, int minute) {
		this(-1, type, hour, minute, System.currentTimeMillis());
	}

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 * @param recurrence
	 * 		Recurrence of the event.
	 * @param reserveLeft
	 * 		The reserve data for some settings.
	 * @param reserveRight
	 * 		The reserve data for some settings.
	 */
	public ScheduleItem(ScheduleType type, int hour, int minute, EventRecurrence recurrence, String reserveLeft, String reserveRight) {
		this(-1, type, hour, minute, System.currentTimeMillis());
		setEventRecurrence(recurrence);
		setReserveLeft(reserveLeft);
		setReserveRight(reserveRight);
	}



	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 * @param editedTime
	 * 		Created time.
	 */
	public ScheduleItem(ScheduleType type, int hour, int minute, long editedTime) {
		this(-1, type, hour, minute, editedTime);
	}

	/**
	 * Get {@link com.schautup.data.ScheduleType}.
	 *
	 * @return {@link com.schautup.data.ScheduleType}.
	 */
	public ScheduleType getType() {
		return mType;
	}

	/**
	 * Set {@link com.schautup.data.ScheduleType}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}.
	 */
	public void setType(ScheduleType type) {
		mType = type;
	}

	/**
	 * Get Hour.
	 *
	 * @return Hour.
	 */
	public int getHour() {
		return mHour;
	}

	/**
	 * Set Hour.
	 *
	 * @param hour
	 * 		Hour.
	 */
	public void setHour(int hour) {
		mHour = hour;
	}

	/**
	 * Get minute.
	 *
	 * @return Minute.
	 */
	public int getMinute() {
		return mMinute;
	}

	/**
	 * Set minute.
	 *
	 * @param minute
	 * 		minute.
	 */
	public void setMinute(int minute) {
		mMinute = minute;
	}

	/**
	 * Get edited time.
	 */
	public long getEditedTime() {
		return mEditedTime;
	}

	/**
	 * Set edited time.
	 * <p/>
	 *
	 * @param editedTime
	 * 		The created time.
	 */
	public void setEditedTime(long editedTime) {
		mEditedTime = editedTime;
	}

	/**
	 * Get database entry id when the item is retrieved from database.
	 *
	 * @return The id that was generated by database after the item was inserted firstly.
	 */
	public long getId() {
		return mId;
	}

	/**
	 * Set database entry id when the item is retrieved from database.
	 *
	 * @param id
	 * 		The id.
	 */
	public void setId(long id) {
		mId = id;
	}

	/**
	 * Set {@link com.doomonafireball.betterpickers.recurrencepicker.EventRecurrence}.
	 *
	 * @param eventRecurrence
	 */
	public void setEventRecurrence(EventRecurrence eventRecurrence) {
		mEventRecurrence = eventRecurrence;
	}

	/**
	 * Get {@link com.doomonafireball.betterpickers.recurrencepicker.EventRecurrence}.
	 *
	 * @return {@link com.doomonafireball.betterpickers.recurrencepicker.EventRecurrence}.
	 */
	public EventRecurrence getEventRecurrence() {
		return mEventRecurrence;
	}

	/**
	 * Get reserve data.
	 *
	 * @return Reserve data.
	 */
	public String getReserveLeft() {
		return mReserveLeft;
	}

	/**
	 * Set reserve data.
	 *
	 * @param reserveLeft
	 * 		Reserve data.
	 */
	public void setReserveLeft(String reserveLeft) {
		mReserveLeft = reserveLeft;
	}

	/**
	 * Get reserve data. This reserve value always provides data type of the value in reserve left.
	 * <p/>
	 * For example. the left reserve is {@code "true"} then the right reserve is {@code "false"}.
	 *
	 * @return Reserve data.
	 */
	public String getReserveRight() {
		return mReserveRight;
	}

	/**
	 * Set reserve data. This reserve value always provides data type of the value in reserve left.
	 * <p/>
	 * For example. the left reserve is {@code "true"} then the right reserve is {@code "false"}.
	 *
	 * @param reserveRight
	 * 		Reserve data.
	 */
	public void setReserveRight(String reserveRight) {
		mReserveRight = reserveRight;
	}
}
