package com.schautup.data;

/**
 * Data structure of a schedule item.
 */
public final class ScheduleItem {
	/**
	 * Possible Id if data instance is from DB.
	 */
	private int mId;
	/**
	 * Different types scheduled.
	 */
	private ScheduleType mType;
	/**
	 * Hour.
	 */
	private int mHour;
	/**
	 * Minute.
	 */
	private int mMinute;
	/**
	 * Edited time.
	 */
	private long mEditedTime;

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param id
	 * 		Possible Id if data instance is from DB.
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 * @param editedTime
	 * 		Created time.
	 */
	public ScheduleItem(int id, ScheduleType type, int hour, int minute, long editedTime) {
		mId = id;
		mType = type;
		mHour = hour;
		mMinute = minute;
		mEditedTime = editedTime;
	}

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param id
	 * 		Possible Id if data instance is from DB.
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 */
	public ScheduleItem(int id, ScheduleType type, int hour, int minute) {
		this(id, type, hour, minute, System.currentTimeMillis());
	}

	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 */
	public ScheduleItem(ScheduleType type, int hour, int minute) {
		this(-1, type, hour, minute, System.currentTimeMillis());
	}


	/**
	 * Constructor of {@link com.schautup.data.ScheduleItem}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}. Different types scheduled.
	 * @param hour
	 * 		Hour.
	 * @param minute
	 * 		Minute.
	 * @param editedTime
	 * 		Created time.
	 */
	public ScheduleItem(ScheduleType type, int hour, int minute, long editedTime) {
		this(-1, type, hour, minute, editedTime);
	}

	/**
	 * Get {@link com.schautup.data.ScheduleType}.
	 *
	 * @return {@link com.schautup.data.ScheduleType}.
	 */
	public ScheduleType getType() {
		return mType;
	}

	/**
	 * Set {@link com.schautup.data.ScheduleType}.
	 *
	 * @param type
	 * 		{@link com.schautup.data.ScheduleType}.
	 */
	public void setType(ScheduleType type) {
		mType = type;
	}

	/**
	 * Get Hour.
	 *
	 * @return Hour.
	 */
	public int getHour() {
		return mHour;
	}

	/**
	 * Set Hour.
	 *
	 * @param hour
	 * 		Hour.
	 */
	public void setHour(int hour) {
		mHour = hour;
	}

	/**
	 * Get minute.
	 *
	 * @return Minute.
	 */
	public int getMinute() {
		return mMinute;
	}

	/**
	 * Set minute.
	 *
	 * @param minute
	 * 		minute.
	 */
	public void setMinute(int minute) {
		mMinute = minute;
	}

	/**
	 * Get edited time.
	 */
	public long getEditedTime() {
		return mEditedTime;
	}

	/**
	 * Set edited time.
	 * <p/>
	 *
	 * @param editedTime
	 * 		The created time.
	 */
	public void setEditedTime(long editedTime) {
		mEditedTime = editedTime;
	}

	/**
	 * Get database entry id when the item is retrieved from database.
	 *
	 * @return The id that was generated by database after the item was inserted firstly.
	 */
	public int getId() {
		return mId;
	}
}
